apiVersion: v1
kind: ServiceAccount
metadata:
  name: unicorn-tp-backend
  namespace: unicorn

---

apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: unicorn-tp-backend
  namespace: unicorn
spec:
  protocol: http

---

apiVersion: v1
kind: Service
metadata:
  name: unicorn-tp-backend
  namespace: unicorn
spec:
  type: NodePort
  selector:
    app: unicorn-tp-backend
  ports:
    - port: 10001
      targetPort: 10001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: unicorn-tp-backend
  namespace: unicorn
  labels:
    app: unicorn-tp-backend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unicorn-tp-backend
  template:
    metadata:
      labels:
        app: unicorn-tp-backend
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
        consul.hashicorp.com/transparent-proxy: 'false'
        consul.hashicorp.com/service-tags: 'dc4,transparent-proxy'
        consul.hashicorp.com/service-meta-version: 'v1'
    spec:
      serviceAccountName: unicorn-tp-backend
      containers:
        - name: unicorn-tp-backend
          image: k3d-doctorconsul.localhost:12345/nicholasjackson/fake-service:v0.25.0
          # imagePullPolicy: Always       # Probably don't need this
          ports:
            - containerPort: 10001
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 10001
            initialDelaySeconds: 10
            periodSeconds: 5
          env:
            - name: 'LISTEN_ADDR'
              value: '0.0.0.0:10001'
            - name: 'NAME'
              value: 'unicorn-backend {Transparent} (DC4)'
            - name: 'MESSAGE'
              value: 'peekaboo'
            - name: 'SERVER_TYPE'
              value: 'grpc'
            - name: 'TIMING_50_PERCENTILE'
              value: '30ms'
            - name: 'TIMING_90_PERCENTILE'
              value: '60ms'
            - name: 'TIMING_99_PERCENTILE'
              value: '90ms'
            - name: 'TIMING_VARIANCE'
              value: '10'
